meta_product_name: "We Meet"
meta_title: "We Meet - Ce soir des verres avec tes potes"
meta_description: "We Meet, l’appli pour aller boire des verres avec tes potes sur un coup de tête, sans te prendre la tête !"
meta_image: "we-meet-fb.jpg"
